#!/usr/bin/env bash
set -e

# Check if `npm` requires `sudo`
if [[ $(which npm) == $HOME* ]]; then
  npm='npm'
else
  npm='sudo npm'
fi

(cd $(dirname $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd));
  # Install global, server-side, node.js dependencies through `npm`
  $npm install -g gulp-cli

  # Install local, server-side, node.js dependencies through `npm`
  npm install)
