#!/usr/bin/env node
console.log(`RUNNING AT: ${process.env.NODE_ENV}`)
if (process.env.NODE_ENV === "development") {
  require("babel-core/register")
  require("./../Main/index").run();
} else {
  require("./../Main/index").run();
}
