#!/usr/bin/env bash
set -e

if [[ $NODE_ENV == 'production' ]]; then
  (cd $(dirname $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd));
    node_modules/.bin/babel-node --experimental -e "require('./src/Main/index').run();" | node_modules/.bin/bunyan)
else
  (cd $(dirname $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd));
    node_modules/.bin/nodemon $@ \
      --exec "node_modules/.bin/babel-node" -- \
      -e "require\(\'./src/Main/index\'\).run\(\);" | node_modules/.bin/bunyan)
fi
