#!/usr/bin/env bash
set -e

# DIR=$(dirname $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd))
# (cd $DIR; NODE_ENV=test script/db-reset)
# (cd $DIR; NODE_ENV=test script/db-migrate up)
(cd $(dirname $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd));
  NODE_ENV=test node_modules/.bin/mocha --timeout 60000 -s 500 -R nyan --recursive --compilers js:babel/register $@ ./test
)
